language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 7.0
  - 7.1

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: vendor/bin/phpspec run
